name: Test packages (3.44.0)
on:
  push:
    branches:
      - master

jobs:
  publish:
    name: Test packages (3.44.0)
    runs-on: ubuntu-latest

    steps:
      - name: Test packages
        uses: nikodembernat/flutter-tools/packages/test@master
        with:
          version: "3.44.0"
